<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="grouppolicy.aspx.cs" Inherits="Boykisser_Website.adminarea.grouppolicy" %>
<asp:Content ContentPlaceHolderID="Content" runat="server">
    <div class="content-wrapper">
        <div class="site-content">
            <h1>Information about Group Policy</h1>
            <div class="cell">
                <p>Group Policy is a feature of Active Directory that allows system administrators to manage settings for users and computers in bulk. A collection of these settings is referred to as a Group Policy Object, or GPO for short. These GPOs can be linked to sites, organizational units (OUs), and domains. This allows admins to fine tune and tailor the user experience based on departmental needs. Group Policy is managed through the Group Policy Management MMC snap-in (gpmc.msc), and you'll usually only be applying GPOs to organizational units. Linking GPOs to the domain is discouraged, since it applies to all users and computers in the domain. An organizational unit is like a special "folder" for Active Directory objects like computers and users and allows for easy management of users and computers. Group Policy applies GPOs in the following order: Local > Site > Domain > OU. Since the GPOs linked to the OU are applied last, they have the most precedence and override any policies that were applied higher up in the hierarchy.</p>
                <br>
                <p>When creating and deploying new configuration changes, never have one GPO configure numerous settings. Instead, use a single GPO for the specific setting you'd like to change, and link it to the OU the policy should apply to. For example, if you want to change Internet Explorer zonemapping settings that apply to Domain Users, you'll create a GPO called "Domain Users - Internet Explorer Zonemapping", and if you want to create a new Registry policy that applies to Domain Users computers, you'll create a GPO called "Domain Users Computers - Registry Policy." This cuts down login times and reduces processing time for policy application, and also allows administrators to easily figure out what a GPO does. The Default Domain Policy (DDP) and Default Domain Controllers Policy (DDCP) are default GPOs created at the time the Active Directory domain was created, and is only ever supposed to be modified for things like user rights assignments, Kerberos policies, lockout and password policies, and is never intended to be used as a "regular" GPO under any circumstance.</p>
                <br>
                <p>The SYSVOL folder is a special folder on all domain controllers in the domain and acts as a storage space for GPOs and their associated files. Each GPO has a corresponding folder in the SYSVOL folder as well as the Active Directory database that contains all of the settings and files associated with that policy. Since all of the domain controllers in the domain need the latest GPOs, a technology called DFS Replication (DFSR) ensures that the SYSVOL folder is automatically updated and kept identical on all domain controllers. Replication of the portion of the GPO stored in Active Directory takes place at the same time as Active Directory replication occurs, since the policies are stored in the Domain Naming Context. It’s important to note that these two replication methods are separate technologies, but complimentary.</p>
            </div>
        </div>
    </div>
</asp:Content>
